### ISSUE TITLE
Error in compiling with HPC

### ISSUE THREAD

**Issue by amirgolp** [aliraeini/porefoam#1]
Hi Ali,

There is a problem with compiling porefoam package on HPC. The operating system they use is CentOS with "module" system to load different packages. I think the Makefile needs to be changed but don't know how exactly. Could you please release a compatible Makefile with CentOS?

Cheers
Amir

**Comment by aliraeini** [comment]
I suspect this has been because of a mistake in the script Makefile.in, requiring additional dependencies for libtiff.  I have updated the code which may have solved the problem.
Alternatively you can remove the thirdparty/libtiff folder and compile the code again.  
The code now requires c++17 (g++ version 7 or higher), BTW.

**Comment by aliraeini** [comment]
I just did a short try of a CentOS docker, it seems it doesn't have libscotch as a yum package. Well it was even worse, Cmake reported that the GCC compiler is broken when compiling zlib, but that shouldn't be the case on your system hopefully.
   
So I think the easiest option for you is to install another fioam-extend and copy/link its Thirdparty folder to the thrirdparty/foamx3m/Thirdparty, which makes foamx3m use the libscotch from there.  For installing foam-extend on CentOS, please see [here](https://openfoamwiki.net/index.php/Installation/Linux/foam-extend-4.1/CentOS).

I will try to update the foamx3m for compiling with MinGW and CentOS based on the link above, but if I get free time - in a couple of months maybe.
